version: "3.9"
services:
  web:
    build: .
    command: sh -c "cd ./my_site_project_folder/ &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 lt_site.wsgi:application"
    volumes:
      - ./:/lt
    expose:
      - 8000

  nginx:
    image: nginx:1.23.2-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./my_site_project_folder/static:/var/www/html/static
      - ./my_site_project_folder/media:/var/www/html/media
      - ./nginx_conf.d:/etc/nginx/conf.d
volumes:
  pg_data:
  static_data:







