# Generated by Django 4.0.4 on 2022-09-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicaltasks', '0002_comment_task_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('undefined', 'Undefined')], default='undefined', help_text='Сложность задачи', max_length=10),
        ),
    ]
