# Generated by Django 4.0.4 on 2022-09-17 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logicaltasks', '0003_alter_task_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='task',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='task_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='likes',
        ),
        migrations.AddField(
            model_name='task',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='task_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
